name: CI Build - Click

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@v3
        
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
          tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Get variable configuration...
        run: |
          echo "BUILD_TIME=$(TZ=Europe/Moscow date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV

      - name: Configuration Environment‌‌...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh

      - name: Start KSU building...
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash kernelsu.sh
          sudo chmod -R 0777 ./*
          echo "RELEASE_NAME=$(cat "$GITHUB_WORKSPACE/out/RELEASETITLE.txt")" >> $GITHUB_ENV
          echo "${{ env.RELEASE_NAME }}"

      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/out/*"
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.BUILD_TIME }}
          allowUpdates: true
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          removeArtifacts: false
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
